spring:
        application:
                name: test
        datasource:
                driver-class-name: com.mysql.jdbc.Driver
                username: root
                password: hjh114423
                url: jdbc:mysql://127.0.0.1:3306/demo_test?characterEncoding=utf-8&useSSL=false
eureka:
        client:
                service-url:
                        defaultZone: http://localhost:8761/eureka
server:
        port: 9000
