spring:
        datasource:
                driver-class-name: com.mysql.jdbc.Driver
                username: root
                password: hjh114432
                url: jdbc:mysql://127.0.0.1/demo_consumer?characterEncoding=utf-8&userSSL=false
