server:
  port: 9999
  
spring:
  application:
    name: consumer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hjh114432
    url: jdbc:mysql://127.0.0.1/demo_consumer?characterEncoding=utf-8&userSSL=false

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true

ribbon:
  eureka:
    enabled: true        
