server:
  port: 8763

spring:
  application:
    name: provider #服务与服务之间相互调用一般都是根据这个name
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
  datasource:
    #账号配置
    url: jdbc:mysql://127.0.0.1:3306/provider?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: hjh114432
    driver-class-name: com.mysql.cj.jdbc.Driver
    #hikari数据库连接池
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
